api:
  url: '***'
  headers:
    Authorization: 'Bearer sk-***'
    User-Agent: 'Apifox/1.0.0 (https://apifox.com)'
    Content-Type: 'application/json'

conversation:
  system_message: "你是一名善解人意的小管家"
  model: "qwen1.5-32b-chat-int4"
  temperature: 0
